# Generated by Django 5.1.5 on 2025-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('new_employee_code', models.CharField(max_length=10)),
                ('old_employee_code', models.CharField(max_length=10)),
                ('sap_code', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('cost_centre_code', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('designation_code', models.CharField(max_length=10)),
                ('reporting_hod_emp_code', models.CharField(max_length=10)),
                ('reporting_hod', models.CharField(max_length=50)),
                ('reporting_designation', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('highest_education', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('last_medical_date', models.DateField()),
                ('locker_no', models.CharField(max_length=10)),
                ('eligibility_for_shoes', models.CharField(max_length=10)),
                ('esic_eligibility', models.CharField(max_length=3)),
                ('esic_number', models.CharField(max_length=20)),
                ('pf_number', models.CharField(max_length=20)),
                ('pf_account_no', models.CharField(max_length=20)),
                ('pf_uan_number', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('aadhaar_card', models.CharField(max_length=12)),
                ('pan_card', models.CharField(max_length=10)),
                ('employee_type', models.CharField(max_length=10)),
                ('contractor_name', models.CharField(max_length=100)),
                ('contractor_code', models.CharField(max_length=10)),
            ],
        ),
    ]
